version: "3.8"
   
services:
    cl:
        image: "cll/app:v0"
        env_file:
            - ./env_vars.txt
        ports:
        -   "80:80"
        depends_on:
            - redis
        container_name: cl

    celery-worker:
        image: "cll/app:v0"
        env_file:
          - ./env_vars.txt
        command:
            sh -c "cd /var/www/concept_lib_sites/v1 &&
                    virtualenv  cllvirenv_v1 &&
                    . cllvirenv_v1/bin/activate &&
                    cd /var/www/concept_lib_sites/v1/CodeListLibrary_project &&
                    celery -A cll worker -l INFO"
        depends_on:
            - cl
        container_name: celery-worker

    celery-beat:
      image: "cll/app:v0"
      env_file:
        - ./env_vars.txt
      command:
        sh -c "cd /var/www/concept_lib_sites/v1 &&
        virtualenv  cllvirenv_v1 &&
        . cllvirenv_v1/bin/activate &&
        cd /var/www/concept_lib_sites/v1/CodeListLibrary_project &&
        celery -A cll beat -l INFO"
      depends_on:
        - cl
      container_name: celery-beat

    redis:
        image: "redis:alpine"
        container_name: redis

