version: "3.8"

services:
  os:
    build: OS/.
    container_name: os

  #database: unless needed dokerized put backup to database_deploy folder
    #build: database_deploy/.
   # volumes:
    #  - ./docker_data/postgres-data:/var/lib/postgresql
    #  - ./docker_data/postgres-logs:/var/log/postgresql
    #  - ./docker_data/postgres-etc:/etc/postgresql
    #  - .:/docker_settings
  #  ports:
  #    - "5432:5432"
  #  restart: unless-stopped
  #  env_file:
  #    - database_deploy/database.env

  cl:
    build: .
    env_file:
      - ./env_vars.txt
    ports:
      - "80:80"
    depends_on:
      - redis
    container_name: cl



  redis:
    image: "redis:alpine"
    container_name: redis

