SET SECRET_KEY=amfHsyJHDDGFFf9GksfoR08jRRr00bd75bbd9876gdG5ffgEEW
SET DEBUG=True
SET DB_NAME=concept_library
SET DB_USER=clluser
SET DB_PASSWORD=P@ssw0rd
SET DB_HOST=localhost
REM SET  change this to True to enable read-only version
SET CLL_READ_ONLY=False
SET ENABLE_PUBLISH=True
SET BROWSABLEAPI=False
SET SHOWADMIN=True
SET ALLOWED_HOSTS=localhost, 127.0.0.1
SET DB_USER_READ_ONLY=clluser_readonly
SET DB_PASSWORD_READ_ONLY=SECRET_KEY=amfHsyJHDDGFFf9GksfoR08jRRr00bd75bbd9876gdG5ffgEEW
SET DEBUG=True
SET DB_NAME=concept_library
SET DB_USER=clluser
SET DB_PASSWORD=P@ssw0rd
SET DB_HOST=localhost
REM SET  change this to True to enable read-only version
SET CLL_READ_ONLY=False
SET ENABLE_PUBLISH=True
SET BROWSABLEAPI=False
SET SHOWADMIN=True
SET ALLOWED_HOSTS=localhost, 127.0.0.1
SET DB_USER_READ_ONLY=clluser_readonly
SET DB_PASSWORD_READ_ONLY=SECRET_KEY=amfHsyJHDDGFFf9GksfoR08jRRr00bd75bbd9876gdG5ffgEEW
SET DEBUG=True
SET DB_NAME=concept_library
SET DB_USER=clluser
SET DB_PASSWORD=P@ssw0rd
SET DB_HOST=localhost
REM SET  change this to True to enable read-only version
SET CLL_READ_ONLY=False
SET ENABLE_PUBLISH=True
SET BROWSABLEAPI=False
SET SHOWADMIN=True
SET ALLOWED_HOSTS=localhost, 127.0.0.1
SET DB_USER_READ_ONLY=clluser_readonly
SET DB_PASSWORD_READ_ONLY=P@ssw0rd
SET UNIT_TEST_DB_NAME=cl_test_database
SET UNIT_TEST_DB_USER=cl_unit_test_user
SET UNIT_TEST_DB_PASSWORD=P@ssw0rd
SET UNIT_TEST_DB_HOST=localhost
SET IS_INSIDE_GATEWAY=False
SET IS_DEVELOPMENT_PC=True
SET IS_DEMO=False
REM SET  disable LDAP auth.
SET ENABLE_LDAP_AUTH=False
SET AUTH_LDAP_BIND_PASSWORD=00000
SET AUTH_LDAP_SERVER_URI=00000
SET AUTH_LDAP_BIND_DN=00000
SET AUTH_LDAP_USER_SEARCH=00000
REM SET  Set up the basic group parameters
SET AUTH_LDAP_GROUP_SEARCH=00000
REM SET  Simple group restrictions
SET AUTH_LDAP_REQUIRE_GROUP=00000 
SET UNIT_TEST_DB_NAME=cl_test_database
SET UNIT_TEST_DB_USER=cl_unit_test_user
SET UNIT_TEST_DB_PASSWORD=P@ssw0rd
SET UNIT_TEST_DB_HOST=localhost
SET IS_INSIDE_GATEWAY=False
SET IS_DEVELOPMENT_PC=True
SET IS_DEMO=False
REM SET  disable LDAP auth.
SET ENABLE_LDAP_AUTH=False
SET AUTH_LDAP_BIND_PASSWORD=00000
SET AUTH_LDAP_SERVER_URI=00000
SET AUTH_LDAP_BIND_DN=00000
SET AUTH_LDAP_USER_SEARCH=00000
REM SET  Set up the basic group parameters
SET AUTH_LDAP_GROUP_SEARCH=00000
REM SET  Simple group restrictions
SET AUTH_LDAP_REQUIRE_GROUP=00000 
SET UNIT_TEST_DB_NAME=cl_test_database
SET UNIT_TEST_DB_USER=cl_unit_test_user
SET UNIT_TEST_DB_PASSWORD=P@ssw0rd
SET UNIT_TEST_DB_HOST=localhost
SET IS_INSIDE_GATEWAY=False
SET IS_DEVELOPMENT_PC=True
SET IS_DEMO=False
REM SET  disable LDAP auth.
SET ENABLE_LDAP_AUTH=False
SET AUTH_LDAP_BIND_PASSWORD=00000
SET AUTH_LDAP_SERVER_URI=00000
SET AUTH_LDAP_BIND_DN=00000
SET AUTH_LDAP_USER_SEARCH=00000
REM SET  Set up the basic group parameters
SET AUTH_LDAP_GROUP_SEARCH=00000
REM SET  Simple group restrictions
SET AUTH_LDAP_REQUIRE_GROUP=00000