version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: ./development/postgres.Dockerfile
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./development/db/:/docker-entrypoint-initdb.d/db/
    env_file:
      - ./development/env/postgres.compose.env
    healthcheck:
      test: [
        "CMD-SHELL",
        "/usr/bin/pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB",
        "&& /usr/bin/psql -d $$POSTGRES_DB -U $$POSTGRES_USER -t -c \"select count(datid) from pg_stat_activity where state is not null and wait_event = 'WalWriterMain';\" | egrep .",
      ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    platform: linux/amd64
    image: cll/app
    build:
      context: ..
      dockerfile: ./docker/test/app.Dockerfile
      args:
        server_name: localhost
    restart: unless-stopped
    command: >
      sh -c "/home/config_cll/init-app.sh"
    ports:
      - 8005:80
    expose:
      - 80
    env_file:
      - ./test/env/app.compose.env
    volumes:
      - ../CodeListLibrary_project/cll/media/:/var/www/concept_lib_sites/v1/CodeListLibrary_project/media
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: unless-stopped
    profiles:
      - live
      - email
    ports:
      - 8025:8025
    networks:
      default:
        aliases:
          - mailhog

  redis:
    image: redis:7.0-bullseye
    container_name: redis
    restart: on-failure
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      default:
        aliases:
          - redis

  celery_worker:
    image: cll/app
    restart: on-failure:2
    command: >
      sh -c "/home/config_cll/worker-start.sh"
    env_file:
      - ./test/env/app.compose.env
    profiles:
      - live
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  celery_beat:
    image: cll/app
    restart: on-failure:2
    command: >
      sh -c "/home/config_cll/beat-start.sh"
    env_file:
      - ./test/env/app.compose.env
    profiles:
      - live
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      celery_worker:
        condition: service_started
