version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: ./development/postgres.Dockerfile
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./development/db/:/docker-entrypoint-initdb.d/db/
    env_file:
      - ./development/env/postgres.compose.env

  app:
    platform: linux/amd64
    image: cll/app
    build:
      context: ..
      dockerfile: ./docker/test/app.Dockerfile
      args:
        server_name: localhost
    restart: on-failure
    command: >
      sh -c "/home/config_cll/init-app.sh"
    ports:
      - 8005:80
    expose:
      - 80
    env_file:
      - ./test/env/app.compose.env
    depends_on:
      - postgres
      - redis
    volumes:
      - ../CodeListLibrary_project/cll/media/:/var/www/concept_lib_sites/v1/CodeListLibrary_project/media

  redis:
    image: redis:7.0-bullseye
    container_name: redis
    restart: on-failure
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      default:
        aliases:
          - redis

  celery_worker:
    image: cll/app
    restart: on-failure:2
    command: >
      sh -c "/home/config_cll/worker-start.sh"
    env_file:
      - ./test/env/app.compose.env
    profiles:
      - live
    depends_on:
      - postgres
      - app
      - redis

  celery_beat:
    image: cll/app
    restart: on-failure:2
    command: >
      sh -c "/home/config_cll/beat-start.sh"
    env_file:
      - ./test/env/app.compose.env
    profiles:
      - live
    depends_on:
      - postgres
      - app
      - redis
      - celery_worker
