version: '3'

services:
  app:
    platform: linux/amd64
    image: cll/os
    restart: on-failure
    command: >
      sh -c "/home/config_cll/init-app.sh"
    volumes:
      - ../CodeListLibrary_project:/var/www/concept_lib_sites/v1/CodeListLibrary_project/
    ports:
      - 8080:80
    expose:
      - 80
      - 443
    env_file:
      - ./production/env/app.compose.env
    depends_on:
      - redis

  redis:
    image: redis:7.0-bullseye
    container_name: redis
    restart: on-failure
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - .:/data
    networks:
      default:
        aliases:
          - redis

  celery_worker:
    image: cll/os_celery_worker
    restart: on-failure:2
    command: >
      sh -c "/home/config_cll/worker-start.sh"
    env_file:
      - ./production/env/app.compose.env
    volumes:
      - ../CodeListLibrary_project:/var/www/concept_lib_sites/v1/CodeListLibrary_project/
    depends_on:
      - app
      - redis

  celery_beat:
    image: cll/os_celery_beat
    restart: on-failure:2
    command: >
      sh -c "/home/config_cll/beat-start.sh"
    env_file:
      - ./production/env/app.compose.env
    volumes:
      - ../CodeListLibrary_project:/var/www/concept_lib_sites/v1/CodeListLibrary_project/
    depends_on:
      - app
      - redis
      - celery_worker
