# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-12-09 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0011_auto_20201203_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalphenotype',
            name='implementation',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='phenotype',
            name='implementation',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalphenotype',
            name='validation',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='validation',
            field=models.CharField(max_length=3000),
        ),
    ]
