# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-12-09 15:17


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0012_auto_20201209_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phenotype',
            name='data_sources',
        ),
    ]
