# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-01-19 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0014_historicalphenotypedatasourcemap_phenotypedatasourcemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalphenotype',
            name='phenoflowid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='phenotype',
            name='phenoflowid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
