# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-02-26 17:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0015_auto_20210119_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalphenotype',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                null=True,
                size=None),
        ),
        migrations.AddField(
            model_name='phenotype',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                null=True,
                size=None),
        ),
    ]
