# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-03-12 17:00
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0016_auto_20210226_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='historicalconcept',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
