# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-03-23 15:18


import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0021_auto_20210323_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalphenotype',
            name='publications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='publications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None),
        ),
    ]
