# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-03-29 14:09

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinicalcode', '0022_auto_20210323_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPhenotypeComponent',
            fields=[
                ('id',
                 models.IntegerField(auto_created=True,
                                     blank=True,
                                     db_index=True,
                                     verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('group_name', models.CharField(max_length=250)),
                ('table_name',
                 models.CharField(blank=True, max_length=250, null=True)),
                ('file_name',
                 models.CharField(blank=True, max_length=250, null=True)),
                ('table_description',
                 models.CharField(blank=True, max_length=1000, null=True)),
                ('concept_ids',
                 django.contrib.postgres.fields.jsonb.JSONField()),
                ('table_data',
                 django.contrib.postgres.fields.jsonb.JSONField()),
                ('history_id',
                 models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason',
                 models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'),
                                           ('-', 'Deleted')],
                                  max_length=1)),
                ('created_by',
                 models.ForeignKey(
                     blank=True,
                     db_constraint=False,
                     null=True,
                     on_delete=django.db.models.deletion.DO_NOTHING,
                     related_name='+',
                     to=settings.AUTH_USER_MODEL)),
                ('history_user',
                 models.ForeignKey(
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     related_name='+',
                     to=settings.AUTH_USER_MODEL)),
                ('modified_by',
                 models.ForeignKey(
                     blank=True,
                     db_constraint=False,
                     null=True,
                     on_delete=django.db.models.deletion.DO_NOTHING,
                     related_name='+',
                     to=settings.AUTH_USER_MODEL)),
                ('phenotype',
                 models.ForeignKey(
                     blank=True,
                     db_constraint=False,
                     null=True,
                     on_delete=django.db.models.deletion.DO_NOTHING,
                     related_name='+',
                     to='clinicalcode.Phenotype')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical phenotype component',
            },
        ),
        migrations.CreateModel(
            name='PhenotypeComponent',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('group_name', models.CharField(max_length=250)),
                ('table_name',
                 models.CharField(blank=True, max_length=250, null=True)),
                ('file_name',
                 models.CharField(blank=True, max_length=250, null=True)),
                ('table_description',
                 models.CharField(blank=True, max_length=1000, null=True)),
                ('concept_ids',
                 django.contrib.postgres.fields.jsonb.JSONField()),
                ('table_data',
                 django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_by',
                 models.ForeignKey(
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     related_name='phenotypecomponents_created',
                     to=settings.AUTH_USER_MODEL)),
                ('modified_by',
                 models.ForeignKey(
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     related_name='phenotypecomponents_modified',
                     to=settings.AUTH_USER_MODEL)),
                ('phenotype',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='clinicalcode.Phenotype')),
            ],
            options={
                'ordering': ('created', ),
            },
        ),
    ]
