# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-05-14 18:40


import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0027_conceptcodeattribute_historicalconceptcodeattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptcodeattribute',
            name='attributes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='historicalconceptcodeattribute',
            name='attributes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, null=True, size=None),
        ),
    ]
