# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-06-09 14:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0029_historicalstatistics_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='about_menu',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True,
                                                                 null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='allowed_tabs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True,
                                                                 null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='site_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalbrand',
            name='about_menu',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True,
                                                                 null=True),
        ),
        migrations.AddField(
            model_name='historicalbrand',
            name='allowed_tabs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True,
                                                                 null=True),
        ),
        migrations.AddField(
            model_name='historicalbrand',
            name='site_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
