# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-07-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0030_auto_20210609_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltag',
            name='tag_type',
            field=models.IntegerField(choices=[(1, b'tag'),
                                               (2, b'collection')],
                                      default=1),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_type',
            field=models.IntegerField(choices=[(1, b'tag'),
                                               (2, b'collection')],
                                      default=1),
        ),
    ]
