# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-08-10 12:40


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0035_auto_20210810_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='friendly_id',
            field=models.CharField(default=b'', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalconcept',
            name='friendly_id',
            field=models.CharField(default=b'', editable=False, max_length=50),
        ),
    ]
