# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-08-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0036_auto_20210810_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalphenotype',
            name='friendly_id',
            field=models.CharField(default=b'', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='phenotype',
            name='friendly_id',
            field=models.CharField(default=b'', editable=False, max_length=50),
        ),
    ]
