# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-08-13 15:11


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0037_auto_20210812_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkingset',
            name='friendly_id',
            field=models.CharField(default=b'', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='workingset',
            name='friendly_id',
            field=models.CharField(default=b'', editable=False, max_length=50),
        ),
    ]
