# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-08-16 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0038_auto_20210813_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedconcept',
            name='code_count',
            field=models.IntegerField(null=True),
        ),
    ]
