# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-08-26 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0039_publishedconcept_code_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='NON_STANDARD_CODES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('import_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('avail_from_dt', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
