# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-09-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0041_auto_20210917_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='historicalconcept',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='historicalphenotype',
            name='implementation',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='implementation',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
