# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-10-05 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0045_auto_20211001_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concepttagmap',
            name='concept',
        ),
        migrations.RemoveField(
            model_name='concepttagmap',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='concepttagmap',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='historicalconcepttagmap',
            name='concept',
        ),
        migrations.RemoveField(
            model_name='historicalconcepttagmap',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalconcepttagmap',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalconcepttagmap',
            name='tag',
        ),
        migrations.DeleteModel(
            name='ConceptTagMap',
        ),
        migrations.DeleteModel(
            name='HistoricalConceptTagMap',
        ),
    ]
