# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-10-19 08:55


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0046_auto_20211005_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptcodeattribute',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalconceptcodeattribute',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
