# Generated by Django 3.2.9 on 2021-11-09 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinicalcode', '0047_auto_20211019_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coderegex',
            name='column_search',
            field=models.IntegerField(blank=True, choices=[(1, 'code'), (2, 'description')], null=True),
        ),
        migrations.AlterField(
            model_name='coderegex',
            name='regex_type',
            field=models.IntegerField(choices=[(1, 'simple (% only)'), (2, 'POSIX regex')]),
        ),
        migrations.AlterField(
            model_name='codingsystemfilter',
            name='type',
            field=models.CharField(choices=[('string', 'string'), ('integer', 'integer'), ('double', 'double'), ('date', 'date'), ('time', 'time'), ('datetime', 'datetime'), ('boolean', 'boolean')], max_length=20),
        ),
        migrations.AlterField(
            model_name='component',
            name='component_type',
            field=models.IntegerField(choices=[(1, 'Concept'), (2, 'Query Builder'), (3, 'Expression'), (4, 'Select/Import')]),
        ),
        migrations.AlterField(
            model_name='component',
            name='concept_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concept_ref', to='clinicalcode.concept'),
        ),
        migrations.AlterField(
            model_name='component',
            name='concept_ref_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clinicalcode.historicalconcept'),
        ),
        migrations.AlterField(
            model_name='component',
            name='logical_type',
            field=models.IntegerField(choices=[(1, 'Add codes'), (2, 'Remove codes')], default=1),
        ),
        migrations.AlterField(
            model_name='concept',
            name='coding_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concepts', to='clinicalcode.codingsystem'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concepts_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='concept',
            name='friendly_id',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='concept',
            name='group_access',
            field=models.IntegerField(choices=[(1, 'No Access'), (2, 'View'), (3, 'Edit')], default=1),
        ),
        migrations.AlterField(
            model_name='concept',
            name='owner_access',
            field=models.IntegerField(choices=[(1, 'No Access'), (2, 'View'), (3, 'Edit')], default=3),
        ),
        migrations.AlterField(
            model_name='concept',
            name='world_access',
            field=models.IntegerField(choices=[(1, 'No Access'), (2, 'View'), (3, 'Edit')], default=1),
        ),
        migrations.AlterField(
            model_name='historicalcoderegex',
            name='column_search',
            field=models.IntegerField(blank=True, choices=[(1, 'code'), (2, 'description')], null=True),
        ),
        migrations.AlterField(
            model_name='historicalcoderegex',
            name='regex_type',
            field=models.IntegerField(choices=[(1, 'simple (% only)'), (2, 'POSIX regex')]),
        ),
        migrations.AlterField(
            model_name='historicalcomponent',
            name='component_type',
            field=models.IntegerField(choices=[(1, 'Concept'), (2, 'Query Builder'), (3, 'Expression'), (4, 'Select/Import')]),
        ),
        migrations.AlterField(
            model_name='historicalcomponent',
            name='logical_type',
            field=models.IntegerField(choices=[(1, 'Add codes'), (2, 'Remove codes')], default=1),
        ),
        migrations.AlterField(
            model_name='historicalconcept',
            name='friendly_id',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalconcept',
            name='group_access',
            field=models.IntegerField(choices=[(1, 'No Access'), (2, 'View'), (3, 'Edit')], default=1),
        ),
        migrations.AlterField(
            model_name='historicalconcept',
            name='owner_access',
            field=models.IntegerField(choices=[(1, 'No Access'), (2, 'View'), (3, 'Edit')], default=3),
        ),
        migrations.AlterField(
            model_name='historicalconcept',
            name='world_access',
            field=models.IntegerField(choices=[(1, 'No Access'), (2, 'View'), (3, 'Edit')], default=1),
        ),
        migrations.AlterField(
            model_name='historicalphenotype',
            name='friendly_id',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalphenotype',
            name='group_access',
            field=models.IntegerField(choices=[(1, 'No Access'), (2, 'View'), (3, 'Edit')], default=1),
        ),
        migrations.AlterField(
            model_name='historicalphenotype',
            name='owner_access',
            field=models.IntegerField(choices=[(1, 'No Access'), (2, 'View'), (3, 'Edit')], default=3),
        ),
        migrations.AlterField(
            model_name='historicalphenotype',
            name='world_access',
            field=models.IntegerField(choices=[(1, 'No Access'), (2, 'View'), (3, 'Edit')], default=1),
        ),
        migrations.AlterField(
            model_name='historicaltag',
            name='display',
            field=models.IntegerField(choices=[(1, 'default'), (2, 'primary'), (3, 'success'), (4, 'info'), (5, 'warning'), (6, 'danger')], default=1),
        ),
        migrations.AlterField(
            model_name='historicaltag',
            name='tag_type',
            field=models.IntegerField(choices=[(1, 'tag'), (2, 'collection')], default=1),
        ),
        migrations.AlterField(
            model_name='historicalworkingset',
            name='friendly_id',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalworkingset',
            name='group_access',
            field=models.IntegerField(choices=[(1, 'No Access'), (2, 'View'), (3, 'Edit')], default=1),
        ),
        migrations.AlterField(
            model_name='historicalworkingset',
            name='owner_access',
            field=models.IntegerField(choices=[(1, 'No Access'), (2, 'View'), (3, 'Edit')], default=3),
        ),
        migrations.AlterField(
            model_name='historicalworkingset',
            name='world_access',
            field=models.IntegerField(choices=[(1, 'No Access'), (2, 'View'), (3, 'Edit')], default=1),
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phenotype_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='friendly_id',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='group_access',
            field=models.IntegerField(choices=[(1, 'No Access'), (2, 'View'), (3, 'Edit')], default=1),
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='owner_access',
            field=models.IntegerField(choices=[(1, 'No Access'), (2, 'View'), (3, 'Edit')], default=3),
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='world_access',
            field=models.IntegerField(choices=[(1, 'No Access'), (2, 'View'), (3, 'Edit')], default=1),
        ),
        migrations.AlterField(
            model_name='tag',
            name='display',
            field=models.IntegerField(choices=[(1, 'default'), (2, 'primary'), (3, 'success'), (4, 'info'), (5, 'warning'), (6, 'danger')], default=1),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_type',
            field=models.IntegerField(choices=[(1, 'tag'), (2, 'collection')], default=1),
        ),
        migrations.AlterField(
            model_name='workingset',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='working_set_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workingset',
            name='friendly_id',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='workingset',
            name='group_access',
            field=models.IntegerField(choices=[(1, 'No Access'), (2, 'View'), (3, 'Edit')], default=1),
        ),
        migrations.AlterField(
            model_name='workingset',
            name='owner_access',
            field=models.IntegerField(choices=[(1, 'No Access'), (2, 'View'), (3, 'Edit')], default=3),
        ),
        migrations.AlterField(
            model_name='workingset',
            name='world_access',
            field=models.IntegerField(choices=[(1, 'No Access'), (2, 'View'), (3, 'Edit')], default=1),
        ),
    ]
