# Generated by Django 3.2.9 on 2021-11-11 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0048_auto_20211109_1556'),
        ('clinicalcode', '0048_auto_20211110_1741'),
    ]

    operations = [
    ]
