# Generated by Django 2.2.24 on 2022-02-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0050_auto_20220203_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpublishedphenotype',
            name='is_approved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='publishedphenotype',
            name='is_approved',
            field=models.IntegerField(default=0),
        ),
    ]
