# Generated by Django 2.2.24 on 2022-02-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0051_auto_20220203_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpublishedphenotype',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='publishedphenotype',
            name='is_approved',
        ),
    ]
