# Generated by Django 2.2.24 on 2022-02-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0052_auto_20220203_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpublishedphenotype',
            name='is_approved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publishedphenotype',
            name='is_approved',
            field=models.IntegerField(default=0),
        ),
    ]
