# Generated by Django 2.2.24 on 2022-02-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0053_auto_20220203_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='datasource_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicaldatasource',
            name='datasource_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
