# Generated by Django 2.2.24 on 2022-02-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0054_auto_20220222_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingsystem',
            name='codingsystem_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicalcodingsystem',
            name='codingsystem_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
