# Generated by Django 2.2.24 on 2022-05-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0056_ctv3_codes_gprd_product_codes_icd_11_codes_icd_9_codes_icpc_2_codes_multilex_codes_oxmis_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codelist',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='concept',
            name='author',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicalcodelist',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicalconcept',
            name='author',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicalphenotype',
            name='author',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='author',
            field=models.CharField(max_length=1000),
        ),
    ]
