# Generated by Django 2.2.24 on 2022-05-25 20:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0057_auto_20220506_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='collections_removed_from_filters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='historicalbrand',
            name='collections_removed_from_filters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
