# Generated by Django 2.2.24 on 2022-05-25 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0058_auto_20220525_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='collections_removed_from_filters',
            new_name='collections_excluded_from_filters',
        ),
        migrations.RenameField(
            model_name='historicalbrand',
            old_name='collections_removed_from_filters',
            new_name='collections_excluded_from_filters',
        ),
    ]
