# Generated by Django 2.2.24 on 2022-05-26 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0059_auto_20220525_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpublishedphenotype',
            old_name='is_approved',
            new_name='approval_status',
        ),
        migrations.RenameField(
            model_name='historicalpublishedphenotype',
            old_name='approved_by',
            new_name='moderator',
        ),
        migrations.RenameField(
            model_name='publishedphenotype',
            old_name='is_approved',
            new_name='approval_status',
        ),
        migrations.RenameField(
            model_name='publishedphenotype',
            old_name='approved_by',
            new_name='moderator',
        ),
    ]
