# Generated by Django 2.2.24 on 2022-06-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0060_auto_20220526_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatasource',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
