# Generated by Django 2.2.24 on 2022-06-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0061_auto_20220601_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='description',
            field=models.TextField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='historicaldatasource',
            name='description',
            field=models.TextField(null=True, blank=True),
        ),
    ]
