# Generated by Django 2.2.24 on 2022-08-11 20:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0063_auto_20220801_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalphenotype',
            name='data_sources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='phenotype',
            name='data_sources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
