# Generated by Django 2.2.24 on 2022-08-15 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0064_auto_20220811_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phenotypedatasourcemap',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='phenotypedatasourcemap',
            name='datasource',
        ),
        migrations.RemoveField(
            model_name='phenotypedatasourcemap',
            name='phenotype',
        ),
        migrations.DeleteModel(
            name='HistoricalPhenotypeDataSourceMap',
        ),
        migrations.DeleteModel(
            name='PhenotypeDataSourceMap',
        ),
    ]
