# Generated by Django 2.2.24 on 2022-09-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0065_auto_20220815_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalphenotype',
            name='phenotype_uuid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='phenotype_uuid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
