# Generated by Django 4.0.7 on 2022-09-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0066_alter_historicalbrand_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalphenotype',
            name='phenotype_uuid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='phenotype_uuid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
