# Generated by Django 4.0.7 on 2022-09-30 20:46

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clinicalcode', '0067_alter_historicalphenotype_phenotype_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhenotypeWorkingset',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('type', models.IntegerField(blank=True, choices=[(0, 'Disease or syndrome '), (1, 'Biomarker'), (2, 'Drug'), (3, 'Lifestyle risk factor'), (4, 'Musculoskeletal'), (5, 'Surgical procedure')], default=0, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('collections', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('publications', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None)),
                ('author', models.CharField(max_length=250)),
                ('citation_requirements', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('data_sources', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('phenotypes_concepts_data', models.JSONField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('owner_access', models.IntegerField(choices=[(1, 'No Access'), (2, 'View'), (3, 'Edit')], default=3)),
                ('group_access', models.IntegerField(choices=[(1, 'No Access'), (2, 'View'), (3, 'Edit')], default=1)),
                ('world_access', models.IntegerField(choices=[(1, 'No Access'), (2, 'View'), (3, 'Edit')], default=1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phenotype_workingset_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phenotype_workingset_deleted', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phenotype_workingset_owned', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phenotype_workingset_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalPublishedWorkingset',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('workingset_history_id', models.IntegerField()),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False, null=True)),
                ('approval_status', models.IntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workingset', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clinicalcode.phenotypeworkingset')),
            ],
            options={
                'verbose_name': 'historical published workingset',
                'verbose_name_plural': 'historical published workingsets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPhenotypeWorkingset',
            fields=[
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('id', models.CharField(db_index=True, editable=False, max_length=50)),
                ('name', models.CharField(max_length=250)),
                ('type', models.IntegerField(blank=True, choices=[(0, 'Disease or syndrome '), (1, 'Biomarker'), (2, 'Drug'), (3, 'Lifestyle risk factor'), (4, 'Musculoskeletal'), (5, 'Surgical procedure')], default=0, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('collections', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('publications', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None)),
                ('author', models.CharField(max_length=250)),
                ('citation_requirements', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('data_sources', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('phenotypes_concepts_data', models.JSONField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('owner_access', models.IntegerField(choices=[(1, 'No Access'), (2, 'View'), (3, 'Edit')], default=3)),
                ('group_access', models.IntegerField(choices=[(1, 'No Access'), (2, 'View'), (3, 'Edit')], default=1)),
                ('world_access', models.IntegerField(choices=[(1, 'No Access'), (2, 'View'), (3, 'Edit')], default=1)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auth.group')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical phenotype workingset',
                'verbose_name_plural': 'historical phenotype workingsets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PublishedWorkingset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workingset_history_id', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True, null=True)),
                ('approval_status', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workingset_owner', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workingset_modified', to=settings.AUTH_USER_MODEL)),
                ('workingset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicalcode.phenotypeworkingset')),
            ],
            options={
                'unique_together': {('workingset', 'workingset_history_id')},
            },
        ),
    ]
