# Generated by Django 4.0.7 on 2022-10-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0069_remove_historicalphenotype_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalphenotype',
            name='id',
            field=models.CharField(db_index=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
