# Generated by Django 4.0.7 on 2022-10-10 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0070_alter_historicalphenotype_id_alter_phenotype_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalphenotype',
            name='friendly_id',
        ),
        migrations.RemoveField(
            model_name='phenotype',
            name='friendly_id',
        ),
    ]
