# Generated by Django 4.0.7 on 2022-10-24 16:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0071_remove_historicalphenotype_friendly_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalphenotype',
            name='collections',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='phenotype',
            name='collections',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
