# Generated by Django 4.0.7 on 2022-10-25 13:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0072_historicalphenotype_collections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='collections',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='historicalconcept',
            name='collections',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
