# Generated by Django 4.0.7 on 2022-12-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0073_concept_collections_historicalconcept_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalphenotypeworkingset',
            name='id',
            field=models.CharField(db_index=True, default=None, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='phenotypeworkingset',
            name='id',
            field=models.CharField(default=None, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
