# Generated by Django 4.0.7 on 2023-01-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0073_concept_collections_historicalconcept_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='citation_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalconcept',
            name='citation_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalphenotype',
            name='citation_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalphenotypeworkingset',
            name='citation_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalphenotypeworkingset',
            name='id',
            field=models.CharField(db_index=True, default=None, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='citation_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phenotypeworkingset',
            name='citation_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phenotypeworkingset',
            name='id',
            field=models.CharField(default=None, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
