# Generated by Django 4.0.7 on 2023-02-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0075_genericentity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericentity',
            name='serial_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='historicalgenericentity',
            name='serial_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
