# Generated by Django 4.0.7 on 2023-02-13 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0075_genericentity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericentity',
            name='template_data2',
        ),
        migrations.RemoveField(
            model_name='historicalgenericentity',
            name='template_data2',
        ),
    ]
