# Generated by Django 4.0.7 on 2023-02-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0076_remove_genericentity_template_data2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltemplate',
            name='definition2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='definition2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
