# Generated by Django 4.0.7 on 2023-02-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0076_historicalpublishedgenericentity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericentity',
            name='template_data2',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgenericentity',
            name='template_data2',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
