# Generated by Django 4.0.7 on 2023-03-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0076_alter_genericentity_entity_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpublishedgenericentity',
            name='entity_prefix',
            field=models.CharField(editable=False, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='publishedgenericentity',
            name='entity_prefix',
            field=models.CharField(editable=False, max_length=4, null=True),
        ),
    ]
