# Generated by Django 4.0.7 on 2023-02-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0077_historicaltemplate_definition2_template_definition2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltemplate',
            name='definition2',
        ),
        migrations.RemoveField(
            model_name='template',
            name='definition2',
        ),
        migrations.AlterField(
            model_name='historicaltemplate',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
