# Generated by Django 4.0.7 on 2023-02-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0077_genericentity_template_data2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericentity',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalgenericentity',
            name='id',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
