# Generated by Django 4.0.7 on 2023-03-06 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinicalcode', '0077_historicalpublishedgenericentity_entity_prefix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltemplate',
            name='entity_count',
        ),
        migrations.RemoveField(
            model_name='historicaltemplate',
            name='entity_prefix',
        ),
        migrations.RemoveField(
            model_name='template',
            name='entity_count',
        ),
        migrations.RemoveField(
            model_name='template',
            name='entity_prefix',
        ),
        migrations.CreateModel(
            name='EntityClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('entity_prefix', models.CharField(max_length=4)),
                ('entity_count', models.BigIntegerField(default=0, editable=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_class_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='historicaltemplate',
            name='entity_class',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clinicalcode.entityclass'),
        ),
        migrations.AddField(
            model_name='template',
            name='entity_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_class_type', to='clinicalcode.entityclass'),
        ),
    ]
