# Generated by Django 4.0.7 on 2023-02-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0078_alter_genericentity_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericentity',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='historicalgenericentity',
            name='modified',
        ),
        migrations.AddField(
            model_name='genericentity',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgenericentity',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
