# Generated by Django 4.0.7 on 2023-02-08 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0079_remove_genericentity_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericentity',
            name='type',
        ),
        migrations.RemoveField(
            model_name='historicalgenericentity',
            name='type',
        ),
    ]
