# Generated by Django 4.0.7 on 2023-02-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0080_remove_genericentity_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltemplate',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='template',
            name='brand',
        ),
        migrations.AlterField(
            model_name='genericentity',
            name='layout',
            field=models.IntegerField(choices=[(1, 'Clinical-Coded Phenotype'), (2, 'Concept'), (3, 'Working Set'), (4, 'NLP Phenotype'), (5, 'Genomic Phenotype')]),
        ),
        migrations.AlterField(
            model_name='historicalgenericentity',
            name='layout',
            field=models.IntegerField(choices=[(1, 'Clinical-Coded Phenotype'), (2, 'Concept'), (3, 'Working Set'), (4, 'NLP Phenotype'), (5, 'Genomic Phenotype')]),
        ),
        migrations.AlterField(
            model_name='historicaltemplate',
            name='layout',
            field=models.IntegerField(choices=[(1, 'Clinical-Coded Phenotype'), (2, 'Concept'), (3, 'Working Set'), (4, 'NLP Phenotype'), (5, 'Genomic Phenotype')]),
        ),
        migrations.AlterField(
            model_name='template',
            name='layout',
            field=models.IntegerField(choices=[(1, 'Clinical-Coded Phenotype'), (2, 'Concept'), (3, 'Working Set'), (4, 'NLP Phenotype'), (5, 'Genomic Phenotype')]),
        ),
    ]
