# Generated by Django 4.0.7 on 2023-02-13 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0081_remove_historicaltemplate_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalphenotypeworkingset',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Disease or syndrome'), (1, 'Biomarker'), (2, 'Drug'), (3, 'Lifestyle risk factor'), (4, 'Musculoskeletal'), (5, 'Surgical procedure')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='phenotypeworkingset',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Disease or syndrome'), (1, 'Biomarker'), (2, 'Drug'), (3, 'Lifestyle risk factor'), (4, 'Musculoskeletal'), (5, 'Surgical procedure')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='collection_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags_collection_brand', to='clinicalcode.brand'),
        ),
    ]
