# Generated by Django 4.0.7 on 2023-02-13 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0082_alter_historicalphenotypeworkingset_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericentity',
            old_name='template_id',
            new_name='template',
        ),
        migrations.RenameField(
            model_name='historicalgenericentity',
            old_name='template_id',
            new_name='template',
        ),
    ]
