# Generated by Django 4.0.7 on 2023-03-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0082_genericentity_clinicalcod_search__a075f3_gin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericentity',
            name='entity_id',
        ),
        migrations.RemoveField(
            model_name='genericentity',
            name='entity_prefix',
        ),
        migrations.RemoveField(
            model_name='historicalgenericentity',
            name='entity_id',
        ),
        migrations.RemoveField(
            model_name='historicalgenericentity',
            name='entity_prefix',
        ),
        migrations.RemoveField(
            model_name='historicalpublishedgenericentity',
            name='entity_prefix',
        ),
        migrations.RemoveField(
            model_name='publishedgenericentity',
            name='entity_prefix',
        ),
        migrations.AlterField(
            model_name='genericentity',
            name='id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalgenericentity',
            name='id',
            field=models.CharField(db_index=True, editable=False, max_length=50),
        ),
    ]
