# Generated by Django 4.0.7 on 2023-03-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0084_historicaltemplate_template_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltemplate',
            name='entity_order',
        ),
        migrations.RemoveField(
            model_name='template',
            name='entity_order',
        ),
    ]
