# Generated by Django 4.0.7 on 2023-03-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0086_remove_historicaltemplate_entity_filters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericentity',
            name='template_version',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalgenericentity',
            name='template_version',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
