# Generated by Django 4.0.7 on 2023-03-14 14:22

import clinicalcode.entity_utils.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0087_genericentity_template_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericentity',
            name='group_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2), ('EDIT', 3)], default=clinicalcode.entity_utils.constants.GROUP_PERMISSIONS['NONE']),
        ),
        migrations.AlterField(
            model_name='genericentity',
            name='owner_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2), ('EDIT', 3)], default=clinicalcode.entity_utils.constants.GROUP_PERMISSIONS['EDIT']),
        ),
        migrations.AlterField(
            model_name='genericentity',
            name='status',
            field=models.IntegerField(choices=[('DRAFT', 1), ('FINAL', 2)], default=clinicalcode.entity_utils.constants.ENTITY_STATUS['DRAFT']),
        ),
        migrations.AlterField(
            model_name='genericentity',
            name='world_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2), ('EDIT', 3)], default=clinicalcode.entity_utils.constants.GROUP_PERMISSIONS['NONE']),
        ),
        migrations.AlterField(
            model_name='historicalgenericentity',
            name='group_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2), ('EDIT', 3)], default=clinicalcode.entity_utils.constants.GROUP_PERMISSIONS['NONE']),
        ),
        migrations.AlterField(
            model_name='historicalgenericentity',
            name='owner_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2), ('EDIT', 3)], default=clinicalcode.entity_utils.constants.GROUP_PERMISSIONS['EDIT']),
        ),
        migrations.AlterField(
            model_name='historicalgenericentity',
            name='status',
            field=models.IntegerField(choices=[('DRAFT', 1), ('FINAL', 2)], default=clinicalcode.entity_utils.constants.ENTITY_STATUS['DRAFT']),
        ),
        migrations.AlterField(
            model_name='historicalgenericentity',
            name='world_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2), ('EDIT', 3)], default=clinicalcode.entity_utils.constants.GROUP_PERMISSIONS['NONE']),
        ),
    ]
