# Generated by Django 4.0.7 on 2023-03-19 14:15

import clinicalcode.entity_utils.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0088_alter_genericentity_group_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='source',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalcomponent',
            name='source',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='component_type',
            field=models.IntegerField(choices=[(1, 'Concept'), (2, 'Query Builder'), (3, 'Expression'), (4, 'Select/Import'), (5, 'Searchterm'), (5, 'File Upload')]),
        ),
        migrations.AlterField(
            model_name='genericentity',
            name='group_access',
            field=models.IntegerField(choices=[('NONE', 1), ('EDIT', 2), ('VIEW', 3)], default=clinicalcode.entity_utils.constants.GROUP_PERMISSIONS['NONE']),
        ),
        migrations.AlterField(
            model_name='genericentity',
            name='owner_access',
            field=models.IntegerField(choices=[('NONE', 1), ('EDIT', 2), ('VIEW', 3)], default=clinicalcode.entity_utils.constants.GROUP_PERMISSIONS['EDIT']),
        ),
        migrations.AlterField(
            model_name='genericentity',
            name='world_access',
            field=models.IntegerField(choices=[('NONE', 1), ('EDIT', 2), ('VIEW', 3)], default=clinicalcode.entity_utils.constants.GROUP_PERMISSIONS['NONE']),
        ),
        migrations.AlterField(
            model_name='historicalcomponent',
            name='component_type',
            field=models.IntegerField(choices=[(1, 'Concept'), (2, 'Query Builder'), (3, 'Expression'), (4, 'Select/Import'), (5, 'Searchterm'), (5, 'File Upload')]),
        ),
        migrations.AlterField(
            model_name='historicalgenericentity',
            name='group_access',
            field=models.IntegerField(choices=[('NONE', 1), ('EDIT', 2), ('VIEW', 3)], default=clinicalcode.entity_utils.constants.GROUP_PERMISSIONS['NONE']),
        ),
        migrations.AlterField(
            model_name='historicalgenericentity',
            name='owner_access',
            field=models.IntegerField(choices=[('NONE', 1), ('EDIT', 2), ('VIEW', 3)], default=clinicalcode.entity_utils.constants.GROUP_PERMISSIONS['EDIT']),
        ),
        migrations.AlterField(
            model_name='historicalgenericentity',
            name='world_access',
            field=models.IntegerField(choices=[('NONE', 1), ('EDIT', 2), ('VIEW', 3)], default=clinicalcode.entity_utils.constants.GROUP_PERMISSIONS['NONE']),
        ),
    ]
