# Generated by Django 4.0.7 on 2023-03-20 11:28

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0089_component_source_historicalcomponent_source_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='icd10_codes_and_titles_and_metadata',
            index=django.contrib.postgres.indexes.GinIndex(fields=['alt_code'], name='icd10_code_ln_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='icd10_codes_and_titles_and_metadata',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='icd10_desc_ln_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='opcs4_codes_and_titles',
            index=django.contrib.postgres.indexes.GinIndex(fields=['code_without_decimal'], name='opcs4_code_ln_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='opcs4_codes_and_titles',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='opcs4_desc_ln_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='read_cd_cv2_scd',
            index=django.contrib.postgres.indexes.GinIndex(fields=['read_code'], name='readv2_code_ln_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='read_cd_cv2_scd',
            index=django.contrib.postgres.indexes.GinIndex(fields=['pref_term_30'], name='readv2_desc_ln_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='read_cd_cv3_terms_scd',
            index=django.contrib.postgres.indexes.GinIndex(fields=['term_id'], name='readv3_code_ln_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='read_cd_cv3_terms_scd',
            index=django.contrib.postgres.indexes.GinIndex(fields=['term_30'], name='readv3_desc_ln_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
