# Generated by Django 4.0.7 on 2023-03-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0091_conceptreviewstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='is_legacy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalconcept',
            name='is_legacy',
            field=models.BooleanField(default=True),
        ),
    ]
