# Generated by Django 4.0.10 on 2023-03-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0092_concept_is_legacy_historicalconcept_is_legacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='component_type',
            field=models.IntegerField(choices=[(1, 'Concept'), (2, 'Query Builder'), (3, 'Expression'), (4, 'Select/Import'), (5, 'Searchterm'), (6, 'File Upload'), (7, 'Concept')]),
        ),
        migrations.AlterField(
            model_name='historicalcomponent',
            name='component_type',
            field=models.IntegerField(choices=[(1, 'Concept'), (2, 'Query Builder'), (3, 'Expression'), (4, 'Select/Import'), (5, 'Searchterm'), (6, 'File Upload'), (7, 'Concept')]),
        ),
    ]
