# Generated by Django 4.0.10 on 2023-03-28 21:12

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0093_alter_component_component_type_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='genericentity',
            index=django.contrib.postgres.indexes.GinIndex(fields=['id'], name='ge_id_ln_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='genericentity',
            index=django.contrib.postgres.indexes.GinIndex(fields=['implementation'], name='ge_impl_ln_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='genericentity',
            index=django.contrib.postgres.indexes.GinIndex(fields=['validation'], name='ge_val_ln_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
