# Generated by Django 4.0.10 on 2023-04-18 10:17

import clinicalcode.entity_utils.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0095_hge_indexing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericentity',
            name='group_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2), ('EDIT', 3)], default=clinicalcode.entity_utils.constants.GROUP_PERMISSIONS['NONE']),
        ),
        migrations.AlterField(
            model_name='genericentity',
            name='owner_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2), ('EDIT', 3)], default=clinicalcode.entity_utils.constants.GROUP_PERMISSIONS['EDIT']),
        ),
        migrations.AlterField(
            model_name='genericentity',
            name='world_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2), ('EDIT', 3)], default=clinicalcode.entity_utils.constants.GROUP_PERMISSIONS['NONE']),
        ),
        migrations.AlterField(
            model_name='historicalgenericentity',
            name='group_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2), ('EDIT', 3)], default=clinicalcode.entity_utils.constants.GROUP_PERMISSIONS['NONE']),
        ),
        migrations.AlterField(
            model_name='historicalgenericentity',
            name='owner_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2), ('EDIT', 3)], default=clinicalcode.entity_utils.constants.GROUP_PERMISSIONS['EDIT']),
        ),
        migrations.AlterField(
            model_name='historicalgenericentity',
            name='world_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2), ('EDIT', 3)], default=clinicalcode.entity_utils.constants.GROUP_PERMISSIONS['NONE']),
        ),
    ]
