# Generated by Django 4.0.10 on 2023-04-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0097_entityclass_created_entityclass_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='footer_images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbrand',
            name='footer_images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
