# Generated by Django 4.0.10 on 2023-05-09 20:38

import clinicalcode.entity_utils.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0099_emis_codes_vision_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericentity',
            name='world_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2)], default=clinicalcode.entity_utils.constants.WORLD_ACCESS_PERMISSIONS['NONE']),
        ),
        migrations.AlterField(
            model_name='historicalgenericentity',
            name='world_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2)], default=clinicalcode.entity_utils.constants.WORLD_ACCESS_PERMISSIONS['NONE']),
        ),
        migrations.AlterField(
            model_name='historicalpublishedgenericentity',
            name='approval_status',
            field=models.IntegerField(choices=[('ANY', -1), ('REQUESTED', 0), ('PENDING', 1), ('APPROVED', 2), ('REJECTED', 3)], default=clinicalcode.entity_utils.constants.APPROVAL_STATUS['REQUESTED']),
        ),
        migrations.AlterField(
            model_name='publishedgenericentity',
            name='approval_status',
            field=models.IntegerField(choices=[('ANY', -1), ('REQUESTED', 0), ('PENDING', 1), ('APPROVED', 2), ('REJECTED', 3)], default=clinicalcode.entity_utils.constants.APPROVAL_STATUS['REQUESTED']),
        ),
    ]
