# Generated by Django 4.0.10 on 2023-04-27 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0100_emis_codes_vision_codes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='is_legacy',
        ),
        migrations.RemoveField(
            model_name='historicalconcept',
            name='is_legacy',
        ),
        migrations.AddField(
            model_name='concept',
            name='phenotype_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_concepts', to='clinicalcode.genericentity'),
        ),
        migrations.AddField(
            model_name='historicalconcept',
            name='phenotype_owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clinicalcode.genericentity'),
        ),
    ]
