# Generated by Django 4.0.10 on 2023-05-09 20:43

import clinicalcode.entity_utils.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0100_alter_genericentity_world_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericentity',
            name='publish_status',
            field=models.IntegerField(choices=[('ANY', -1), ('REQUESTED', 0), ('PENDING', 1), ('APPROVED', 2), ('REJECTED', 3)], default=clinicalcode.entity_utils.constants.APPROVAL_STATUS['REQUESTED']),
        ),
        migrations.AddField(
            model_name='historicalgenericentity',
            name='publish_status',
            field=models.IntegerField(choices=[('ANY', -1), ('REQUESTED', 0), ('PENDING', 1), ('APPROVED', 2), ('REJECTED', 3)], default=clinicalcode.entity_utils.constants.APPROVAL_STATUS['REQUESTED']),
        ),
    ]
