# Generated by Django 4.0.10 on 2023-05-26 11:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0104_remove_concept_is_legacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericentity',
            name='brands',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='historicalgenericentity',
            name='brands',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
