# Generated by Django 4.1.10 on 2023-08-29 11:23

import clinicalcode.entity_utils.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0107_brand_index_path_historicalbrand_index_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='group_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2), ('EDIT', 3)], default=clinicalcode.entity_utils.constants.GROUP_PERMISSIONS['NONE']),
        ),
        migrations.AlterField(
            model_name='concept',
            name='owner_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2), ('EDIT', 3)], default=clinicalcode.entity_utils.constants.OWNER_PERMISSIONS['EDIT']),
        ),
        migrations.AlterField(
            model_name='concept',
            name='world_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2)], default=clinicalcode.entity_utils.constants.WORLD_ACCESS_PERMISSIONS['NONE']),
        ),
        migrations.AlterField(
            model_name='historicalconcept',
            name='group_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2), ('EDIT', 3)], default=clinicalcode.entity_utils.constants.GROUP_PERMISSIONS['NONE']),
        ),
        migrations.AlterField(
            model_name='historicalconcept',
            name='owner_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2), ('EDIT', 3)], default=clinicalcode.entity_utils.constants.OWNER_PERMISSIONS['EDIT']),
        ),
        migrations.AlterField(
            model_name='historicalconcept',
            name='world_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2)], default=clinicalcode.entity_utils.constants.WORLD_ACCESS_PERMISSIONS['NONE']),
        ),
        migrations.AlterField(
            model_name='historicalphenotype',
            name='group_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2), ('EDIT', 3)], default=clinicalcode.entity_utils.constants.GROUP_PERMISSIONS['NONE']),
        ),
        migrations.AlterField(
            model_name='historicalphenotype',
            name='owner_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2), ('EDIT', 3)], default=clinicalcode.entity_utils.constants.OWNER_PERMISSIONS['EDIT']),
        ),
        migrations.AlterField(
            model_name='historicalphenotype',
            name='world_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2)], default=clinicalcode.entity_utils.constants.WORLD_ACCESS_PERMISSIONS['NONE']),
        ),
        migrations.AlterField(
            model_name='historicalphenotypeworkingset',
            name='group_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2), ('EDIT', 3)], default=clinicalcode.entity_utils.constants.GROUP_PERMISSIONS['NONE']),
        ),
        migrations.AlterField(
            model_name='historicalphenotypeworkingset',
            name='owner_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2), ('EDIT', 3)], default=clinicalcode.entity_utils.constants.OWNER_PERMISSIONS['EDIT']),
        ),
        migrations.AlterField(
            model_name='historicalphenotypeworkingset',
            name='world_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2)], default=clinicalcode.entity_utils.constants.WORLD_ACCESS_PERMISSIONS['NONE']),
        ),
        migrations.AlterField(
            model_name='historicalworkingset',
            name='group_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2), ('EDIT', 3)], default=clinicalcode.entity_utils.constants.GROUP_PERMISSIONS['NONE']),
        ),
        migrations.AlterField(
            model_name='historicalworkingset',
            name='owner_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2), ('EDIT', 3)], default=clinicalcode.entity_utils.constants.OWNER_PERMISSIONS['EDIT']),
        ),
        migrations.AlterField(
            model_name='historicalworkingset',
            name='world_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2)], default=clinicalcode.entity_utils.constants.WORLD_ACCESS_PERMISSIONS['NONE']),
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='group_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2), ('EDIT', 3)], default=clinicalcode.entity_utils.constants.GROUP_PERMISSIONS['NONE']),
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='owner_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2), ('EDIT', 3)], default=clinicalcode.entity_utils.constants.OWNER_PERMISSIONS['EDIT']),
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='world_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2)], default=clinicalcode.entity_utils.constants.WORLD_ACCESS_PERMISSIONS['NONE']),
        ),
        migrations.AlterField(
            model_name='phenotypeworkingset',
            name='group_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2), ('EDIT', 3)], default=clinicalcode.entity_utils.constants.GROUP_PERMISSIONS['NONE']),
        ),
        migrations.AlterField(
            model_name='phenotypeworkingset',
            name='owner_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2), ('EDIT', 3)], default=clinicalcode.entity_utils.constants.OWNER_PERMISSIONS['EDIT']),
        ),
        migrations.AlterField(
            model_name='phenotypeworkingset',
            name='world_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2)], default=clinicalcode.entity_utils.constants.WORLD_ACCESS_PERMISSIONS['NONE']),
        ),
        migrations.AlterField(
            model_name='workingset',
            name='group_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2), ('EDIT', 3)], default=clinicalcode.entity_utils.constants.GROUP_PERMISSIONS['NONE']),
        ),
        migrations.AlterField(
            model_name='workingset',
            name='owner_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2), ('EDIT', 3)], default=clinicalcode.entity_utils.constants.OWNER_PERMISSIONS['EDIT']),
        ),
        migrations.AlterField(
            model_name='workingset',
            name='world_access',
            field=models.IntegerField(choices=[('NONE', 1), ('VIEW', 2)], default=clinicalcode.entity_utils.constants.WORLD_ACCESS_PERMISSIONS['NONE']),
        ),
    ]
