# Generated by Django 4.1.10 on 2023-09-18 08:54

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0109_read_cd_cv2_scd_description_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='read_cd_cv2_scd',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='readv2_defn_ln_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='read_cd_cv3_terms_scd',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='readv3_defn_ln_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
