# Generated by Django 4.1.10 on 2024-02-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0110_read_cd_cv2_scd_readv2_defn_ln_gin_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltemplate',
            name='hide_on_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='hide_on_create',
            field=models.BooleanField(default=False),
        ),
    ]
