# Generated by Django 4.1.10 on 2024-03-04 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0112_dmd_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='OntologyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('type_id', models.IntegerField(choices=[('CLINICAL_DISEASE', 0), ('CLINICAL_DOMAIN', 1), ('CLINICAL_FUNCTIONAL_ANATOMY', 2)])),
                ('atlas_id', models.IntegerField(blank=True, null=True)),
                ('properties', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ('type_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OntologyTagEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_edges', to='clinicalcode.ontologytag')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_edges', to='clinicalcode.ontologytag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ontologytag',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', through='clinicalcode.OntologyTagEdge', to='clinicalcode.ontologytag'),
        ),
    ]
