# Generated by Django 4.1.10 on 2024-03-05 09:06

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0113_ontologytag_ontologytagedge_ontologytag_children'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ontologytag',
            index=models.Index(fields=['id', 'type_id'], name='clinicalcod_id_d32433_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologytag',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='ot_name_gin_idx'),
        ),
    ]
