# Generated by Django 4.1.10 on 2024-05-13 10:14

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0113_drop_ontology'),
    ]

    operations = [
        migrations.CreateModel(
            name='OntologyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('type_id', models.IntegerField(choices=[('CLINICAL_DISEASE', 0), ('CLINICAL_DOMAIN', 1), ('CLINICAL_FUNCTIONAL_ANATOMY', 2)])),
                ('properties', models.JSONField(blank=True, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('type_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OntologyTagEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_edges', to='clinicalcode.ontologytag')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_edges', to='clinicalcode.ontologytag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ontologytag',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', through='clinicalcode.OntologyTagEdge', to='clinicalcode.ontologytag'),
        ),
        migrations.AddIndex(
            model_name='ontologytag',
            index=models.Index(fields=['id'], name='clinicalcod_id_c1386a_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologytag',
            index=models.Index(fields=['reference_id'], name='clinicalcod_referen_b26caf_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologytag',
            index=models.Index(fields=['id', 'type_id'], name='clinicalcod_id_d32433_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologytag',
            index=models.Index(fields=['id', 'reference_id'], name='clinicalcod_id_7584d4_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologytag',
            index=models.Index(fields=['id', 'type_id', 'reference_id'], name='clinicalcod_id_b41ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologytag',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='ot_name_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologytag',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='clinicalcod_search__2a66db_gin'),
        ),
    ]
