# Generated by Django 4.1.10 on 2024-04-25 14:04

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0114_ontologytag_clinicalcod_id_d32433_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontologytag',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='ontologytag',
            index=models.Index(fields=['id'], name='clinicalcod_id_c1386a_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologytag',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='clinicalcod_search__2a66db_gin'),
        ),
    ]
