# Generated by Django 5.1.2 on 2024-10-24 14:23

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0116_ontology_descendants'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='icd_9_codes',
            index=django.contrib.postgres.indexes.GinIndex(fields=['code'], name='icd9_code_ln_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='icd_9_codes',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='icd9_desc_ln_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
