# Generated by Django 5.1.2 on 2024-11-04 20:13

import datetime
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0117_icd_9_codes_icd9_code_ln_gin_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MESH_CODES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('parent_codes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('record_type', models.IntegerField(blank=True, default=0, null=True)),
                ('record_category', models.IntegerField(blank=True, default=0, null=True)),
                ('record_modifier', models.IntegerField(blank=True, default=0, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('effective_time', models.DateField(blank=True, default=datetime.date.today, null=True)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['code'], name='mesh_code_ln_gin_idx', opclasses=['gin_trgm_ops']), django.contrib.postgres.indexes.GinIndex(fields=['description'], name='mesh_desc_ln_gin_idx', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
