# Generated by Django 5.1.2 on 2024-11-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0117_organisation_genericentity_organisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='org_user_managed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbrand',
            name='org_user_managed',
            field=models.BooleanField(default=False),
        ),
    ]
