# Generated by Django 5.1.2 on 2024-11-27 21:34

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0118_mesh_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATCDDD_CODES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('ddd', models.CharField(blank=True, max_length=64, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=255, null=True)),
                ('administration_route', models.CharField(blank=True, max_length=64, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['code'], name='atcddd_cd_ln_gin_idx', opclasses=['gin_trgm_ops']), django.contrib.postgres.indexes.GinIndex(fields=['description'], name='atcddd_lds_ln_gin_idx', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.CreateModel(
            name='ICD10CA_CODES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('long_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['code'], name='icd10ca_cd_ln_gin_idx', opclasses=['gin_trgm_ops']), django.contrib.postgres.indexes.GinIndex(fields=['description'], name='icd10ca_lds_ln_gin_idx', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.CreateModel(
            name='ICD10CM_CODES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['code'], name='icd10cm_cd_ln_gin_idx', opclasses=['gin_trgm_ops']), django.contrib.postgres.indexes.GinIndex(fields=['description'], name='icd10cm_lds_ln_gin_idx', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
