# Generated by Django 5.1.2 on 2024-12-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0119_atcddd_codes_icd10ca_codes_icd10cm_codes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ontologytag',
            index=models.Index(fields=['type_id'], name='clinicalcod_type_id_c68d0b_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologytagedge',
            index=models.Index(fields=['child_id'], name='clinicalcod_child_i_3ef6e7_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologytagedge',
            index=models.Index(fields=['parent_id'], name='clinicalcod_parent__d845e8_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologytagedge',
            index=models.Index(fields=['child_id', 'parent_id'], name='clinicalcod_child_i_12f0e9_idx'),
        ),
    ]
