# Generated by Django 5.1.2 on 2025-01-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0118_brand_org_user_managed_and_more'),
        ('clinicalcode', '0120_ontologytag_clinicalcod_type_id_c68d0b_idx_and_more'),
    ]

    operations = [
    ]
