# Generated by Django 5.1.2 on 2024-11-26 22:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0120_ontologytag_clinicalcod_type_id_c68d0b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_organisations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='genericentity',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='clinicalcode.organisation'),
        ),
        migrations.AddField(
            model_name='historicalgenericentity',
            name='organisation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clinicalcode.organisation'),
        ),
        migrations.CreateModel(
            name='OrganisationAuthority',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('can_post', models.BooleanField(default=False)),
                ('can_moderate', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicalcode.brand')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicalcode.organisation')),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='brands',
            field=models.ManyToManyField(related_name='organisations', through='clinicalcode.OrganisationAuthority', to='clinicalcode.brand'),
        ),
        migrations.CreateModel(
            name='OrganisationInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.IntegerField(choices=[(0, 'EXPIRED'), (1, 'ACTIVE'), (2, 'SEEN'), (3, 'ACCEPTED'), (4, 'REJECTED')], default=1)),
                ('sent', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('organisation', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to='clinicalcode.organisation')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation_invites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationMembership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.IntegerField(choices=[(0, 'MEMBER'), (1, 'EDITOR'), (2, 'MODERATOR'), (3, 'ADMIN')], default=0)),
                ('joined', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicalcode.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='members',
            field=models.ManyToManyField(related_name='organisations', through='clinicalcode.OrganisationMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
