# Generated by Django 5.1.2 on 2025-03-14 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0122_brand_org_user_managed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='css_path',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='owner',
        ),
        migrations.AddField(
            model_name='brand',
            name='admins',
            field=models.ManyToManyField(related_name='administered_brands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brand',
            name='overrides',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalBrand',
        ),
    ]
