# Generated by Django 5.1.2 on 2025-03-16 18:16

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0123_remove_brand_css_path_remove_brand_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HDRNSite',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='site_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='datasource_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicaldatasource',
            name='datasource_id',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='HDRNDataCategory',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['name'], name='hdrn_dcnm_trgm_idx', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.CreateModel(
            name='HDRNDataAsset',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('hdrn_id', models.IntegerField(blank=True, null=True)),
                ('hdrn_uuid', models.UUIDField(blank=True, null=True)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('years', models.CharField(blank=True, max_length=256, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=2048, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('collection_period', models.TextField(blank=True, null=True)),
                ('data_level', models.CharField(blank=True, max_length=256, null=True)),
                ('data_categories', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_assets', to='clinicalcode.hdrnsite')),
            ],
            options={
                'ordering': ('name',),
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['name'], name='hdrn_danm_trgm_idx', opclasses=['gin_trgm_ops']), django.contrib.postgres.indexes.GinIndex(fields=['data_categories'], name='hdrn_dadc_arr_idx', opclasses=['array_ops'])],
            },
        ),
    ]
