# Generated by Django 5.1.2 on 2025-03-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0124_hdrnsite_brand_site_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_administrable',
            field=models.BooleanField(default=False),
        ),
    ]
