# Generated by Django 5.1.2 on 2025-03-24 14:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0125_brand_is_administrable'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltemplate',
            name='brands',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='template',
            name='brands',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
