# Generated by Django 5.1.2 on 2025-03-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0126_historicaltemplate_brands_template_brands'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('name',), 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
    ]
