# Generated by Django 5.1.2 on 2025-03-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0127_alter_brand_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hdrndataasset',
            options={'ordering': ('name',), 'verbose_name': 'HDRN Data Asset', 'verbose_name_plural': 'HDRN Data Assets'},
        ),
        migrations.AlterModelOptions(
            name='hdrndatacategory',
            options={'verbose_name': 'HDRN Data Category', 'verbose_name_plural': 'HDRN Data Categories'},
        ),
        migrations.AlterModelOptions(
            name='hdrnsite',
            options={'verbose_name': 'HDRN Site', 'verbose_name_plural': 'HDRN Sites'},
        ),
        migrations.AlterModelOptions(
            name='historicaltag',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Tag', 'verbose_name_plural': 'historical Tags'},
        ),
        migrations.AlterModelOptions(
            name='historicaltemplate',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Template', 'verbose_name_plural': 'historical Templates'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('description',), 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ('name',), 'verbose_name': 'Template', 'verbose_name_plural': 'Templates'},
        ),
    ]
