# Generated by Django 5.1.2 on 2025-03-28 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0128_alter_hdrndataasset_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='accessible_brands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brand',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='administered_brands', to=settings.AUTH_USER_MODEL),
        ),
    ]
