# Generated by Django 5.1.8 on 2025-04-20 14:15

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0129_brand_users_alter_brand_admins'),
    ]

    operations = [
        migrations.CreateModel(
            name='HDRNJurisdiction',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'HDRN Jurisdiction',
                'verbose_name_plural': 'HDRN Jurisdictions',
            },
        ),
        migrations.RemoveField(
            model_name='hdrndataasset',
            name='region',
        ),
        migrations.AddField(
            model_name='hdrnsite',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ontologytag',
            name='type_id',
            field=models.IntegerField(choices=[('CLINICAL_DISEASE', 0), ('CLINICAL_DOMAIN', 1), ('CLINICAL_FUNCTIONAL_ANATOMY', 2), ('MESH_CODES', 3)]),
        ),
        migrations.CreateModel(
            name='CCI_CODES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('extent', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['code'], name='hcci_cd_ln_gin_idx', opclasses=['gin_trgm_ops']), django.contrib.postgres.indexes.GinIndex(fields=['description'], name='hcci_lds_ln_gin_idx', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.AddField(
            model_name='hdrndataasset',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='data_assets', to='clinicalcode.hdrnjurisdiction'),
        ),
        migrations.CreateModel(
            name='PHYSICIAN_FEE_CODES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['code'], name='hpfc_cd_ln_gin_idx', opclasses=['gin_trgm_ops']), django.contrib.postgres.indexes.GinIndex(fields=['description'], name='hpfc_lds_ln_gin_idx', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
