# Generated by Django 5.1.8 on 2025-06-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0130_hdrnjurisdiction_remove_hdrndataasset_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericentity',
            name='group_access',
            field=models.IntegerField(choices=[(1, 'NONE'), (2, 'VIEW'), (3, 'EDIT')], default=1),
        ),
        migrations.AlterField(
            model_name='genericentity',
            name='owner_access',
            field=models.IntegerField(blank=True, choices=[(1, 'NONE'), (2, 'VIEW'), (3, 'EDIT')], default=3, null=True),
        ),
        migrations.AlterField(
            model_name='genericentity',
            name='world_access',
            field=models.IntegerField(blank=True, choices=[(1, 'NONE'), (2, 'VIEW')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgenericentity',
            name='group_access',
            field=models.IntegerField(choices=[(1, 'NONE'), (2, 'VIEW'), (3, 'EDIT')], default=1),
        ),
        migrations.AlterField(
            model_name='historicalgenericentity',
            name='owner_access',
            field=models.IntegerField(blank=True, choices=[(1, 'NONE'), (2, 'VIEW'), (3, 'EDIT')], default=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgenericentity',
            name='world_access',
            field=models.IntegerField(blank=True, choices=[(1, 'NONE'), (2, 'VIEW')], default=1, null=True),
        ),
    ]
