# Generated by Django 5.1.8 on 2025-08-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0131_alter_genericentity_group_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericentity',
            name='doi',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgenericentity',
            name='doi',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='QueuedDOI',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trg_id', models.CharField(max_length=50)),
                ('trg_ver', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['id'], name='clinicalcod_id_9e9ffb_idx'), models.Index(fields=['trg_id'], name='clinicalcod_trg_id_0abb38_idx'), models.Index(fields=['trg_ver'], name='clinicalcod_trg_ver_bf7c07_idx'), models.Index(fields=['modified'], name='clinicalcod_modifie_13b621_idx'), models.Index(fields=['trg_id', 'trg_ver'], name='clinicalcod_trg_id_397e3d_idx'), models.Index(fields=['trg_id', 'trg_ver', 'modified'], name='clinicalcod_trg_id_833cf6_idx')],
                'unique_together': {('trg_id', 'trg_ver')},
            },
        ),
    ]
