# Generated by Django 5.1.8 on 2026-01-21 16:19

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0132_genericentity_doi_historicalgenericentity_doi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OMOP_CODES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=64, null=True, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('is_code', models.BooleanField(default=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('standard_concept', models.CharField(blank=True, choices=[('S', 'Standard Concept'), ('C', 'Classification Concept')], default=None, max_length=1, null=True)),
                ('coding_name', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('domain_name', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('class_name', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('vocabulary_name', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('vocabulary_code', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('vocabulary_version', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('valid_start_date', models.DateField(blank=True, null=True)),
                ('valid_end_date', models.DateField(blank=True, null=True)),
                ('invalid_reason', models.CharField(blank=True, choices=[('D', 'Deprecated'), ('U', 'Upgraded')], default=None, max_length=1, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('coding_system', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='omop_code', to='clinicalcode.codingsystem')),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['id'], name='clinicalcod_id_c9ceec_idx'), models.Index(fields=['created'], name='clinicalcod_created_539017_idx'), django.contrib.postgres.indexes.GinIndex(fields=['code'], name='omop_cd_trgm_idx', opclasses=['gin_trgm_ops']), django.contrib.postgres.indexes.GinIndex(fields=['description'], name='omop_desc_trgm_idx', opclasses=['gin_trgm_ops']), django.contrib.postgres.indexes.GinIndex(fields=['coding_name'], name='omop_cs_trgm_idx', opclasses=['gin_trgm_ops']), django.contrib.postgres.indexes.GinIndex(fields=['vocabulary_code'], name='omop_vscd_trgm_idx', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
