# Generated by Django 5.1.8 on 2026-02-09 14:32

import datetime
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0133_omop_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omop_codes',
            name='valid_end_date',
            field=models.DateField(blank=True, default=datetime.date(2099, 12, 31)),
        ),
        migrations.CreateModel(
            name='OMOPRelationships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('relationship', models.CharField(max_length=64)),
                ('valid_start_date', models.DateField(auto_now_add=True)),
                ('valid_end_date', models.DateField(blank=True, default=datetime.date(2099, 12, 31))),
                ('invalid_reason', models.CharField(blank=True, choices=[('D', 'Deprecated'), ('U', 'Upgraded')], default=None, max_length=1, null=True)),
                ('code0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_relationships', to='clinicalcode.omop_codes', to_field='code')),
                ('code1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_relationships', to='clinicalcode.omop_codes', to_field='code')),
            ],
            options={
                'indexes': [models.Index(fields=['code0'], name='clinicalcod_code0_i_9f4db1_idx'), models.Index(fields=['code1'], name='clinicalcod_code1_i_fbd524_idx'), models.Index(fields=['code0', 'code1'], name='clinicalcod_code0_i_634ab7_idx'), models.Index(fields=['code0', 'relationship', 'invalid_reason'], name='clinicalcod_code0_i_bea734_idx'), django.contrib.postgres.indexes.GinIndex(fields=['code0'], name='omop_e0_trgm_idx', opclasses=['gin_trgm_ops']), django.contrib.postgres.indexes.GinIndex(fields=['code0', 'relationship', 'invalid_reason'], name='omop_e0t_tgbt_idx', opclasses=['', 'gin_trgm_ops', ''])],
                'unique_together': {('code0', 'code1', 'relationship')},
            },
        ),
    ]
