# Generated by Django 5.2.12 on 2026-05-05 15:25

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0134_alter_omop_codes_valid_end_date_omoprelationships'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ontologytag',
            name='clinicalcod_id_c1386a_idx',
        ),
        migrations.RemoveIndex(
            model_name='ontologytag',
            name='clinicalcod_referen_b26caf_idx',
        ),
        migrations.RemoveIndex(
            model_name='ontologytag',
            name='clinicalcod_id_d32433_idx',
        ),
        migrations.RemoveIndex(
            model_name='ontologytag',
            name='clinicalcod_id_7584d4_idx',
        ),
        migrations.RemoveIndex(
            model_name='ontologytag',
            name='clinicalcod_id_b41ffe_idx',
        ),
        migrations.RemoveIndex(
            model_name='ontologytag',
            name='ot_name_gin_idx',
        ),
        migrations.RemoveIndex(
            model_name='ontologytag',
            name='clinicalcod_propert_1c7b9b_gin',
        ),
        migrations.RemoveIndex(
            model_name='ontologytag',
            name='clinicalcod_type_id_c68d0b_idx',
        ),
        migrations.RemoveIndex(
            model_name='ontologytagedge',
            name='clinicalcod_child_i_3ef6e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='ontologytagedge',
            name='clinicalcod_parent__d845e8_idx',
        ),
        migrations.RemoveIndex(
            model_name='ontologytagedge',
            name='clinicalcod_child_i_12f0e9_idx',
        ),
        migrations.RenameIndex(
            model_name='ontologytag',
            new_name='ot_gin_srch_idx',
            old_name='clinicalcod_search__2a66db_gin',
        ),
        migrations.RenameIndex(
            model_name='ontologytag',
            new_name='ot_gin_syns_idx',
            old_name='clinicalcod_synonym_0251f3_gin',
        ),
        migrations.RenameIndex(
            model_name='ontologytag',
            new_name='ot_gin_rels_idx',
            old_name='clinicalcod_relatio_da4939_gin',
        ),
        migrations.AlterField(
            model_name='ontologytag',
            name='type_id',
            field=models.IntegerField(choices=[('MONDO', 0), ('MESH', 1), ('SNOMED', 2), ('DOMAIN', 3), ('CATEGORY', 4)]),
        ),
        migrations.AlterField(
            model_name='ontologytag',
            name='reference_id',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='ontologytag',
            unique_together={('type_id', 'reference_id')},
        ),
        migrations.AddIndex(
            model_name='ontologytag',
            index=django.contrib.postgres.indexes.HashIndex(fields=['id'], name='ot_hh_id_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologytag',
            index=django.contrib.postgres.indexes.HashIndex(fields=['type_id'], name='ot_bt_tp_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologytag',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['reference_id'], name='ot_bt_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologytag',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(models.F('properties__xrefs'), name='jsonb_path_ops'), name='ot_gin_jref_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologytag',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(models.F('properties__synonyms'), name='jsonb_path_ops'), name='ot_gin_jsyn_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologytag',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(models.F('properties__categories'), name='jsonb_path_ops'), name='ot_gin_jcat_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologytag',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(models.F('properties__definition'), name='jsonb_path_ops'), name='ot_gin_jdef_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologytag',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['type_id', 'reference_id'], name='ot_cpbt_tr_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologytag',
            index=models.Index(fields=['id'], include=('name', 'type_id', 'reference_id'), name='ot_cv_id_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologytag',
            index=models.Index(fields=['type_id'], include=('id', 'name', 'reference_id'), name='ot_cv_tid_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologytag',
            index=models.Index(fields=['reference_id'], include=('id', 'name', 'type_id'), name='ot_cv_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologytag',
            index=models.Index(fields=['type_id', 'reference_id'], include=('id', 'name'), name='ot_cv_tr_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologytagedge',
            index=django.contrib.postgres.indexes.HashIndex(fields=['id'], name='oe_hh_id_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologytagedge',
            index=django.contrib.postgres.indexes.HashIndex(fields=['child_id'], name='oe_hh_chid_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologytagedge',
            index=django.contrib.postgres.indexes.HashIndex(fields=['parent_id'], name='oe_hh_prid_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologytagedge',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['child_id', 'parent_id'], name='oe_cpbt_chpr_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologytagedge',
            index=models.Index(fields=['child_id'], include=('id', 'parent_id'), name='oe_cv_ch_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologytagedge',
            index=models.Index(fields=['parent_id'], include=('id', 'child_id'), name='oe_cv_pr_idx'),
        ),
    ]
