from django.db import migrations

class Migration(migrations.Migration):
    """
        Creates the `public.ontology_en` text search dictionary from `MONDO`_ ontological terms.

        Requires the following files to exist in the Postgres instance's `/usr/share/postgresql/17/tsearch_data/`:
        - `en_gb.dict` → the large `GB hunspell dictionary`_ dictionary file describing words and flags _etc_.
        - `en_gb.affix` → the large `GB hunspell dictionary`_ affix file describing prefixes, suffixes and encoding _etc_.
        - `en_ontology.ths` → the `ontological thesaurus`_ generated by `Zondo`_

        .. _MONDO: https://www.ebi.ac.uk/ols4/ontologies/mondo
        .. _ontological thesaurus: https://www.postgresql.org/docs/current/textsearch-dictionaries.html#TEXTSEARCH-THESAURUS
        .. _Zondo: https://github.com/JackScanlon/Zondo
        .. _GB hunspell dictionary: https://wordlist.aspell.net/dicts/
    """

    dependencies = [
        ('clinicalcode', '0135_remove_ontologytag_clinicalcod_id_c1386a_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            --[!] create ts agg if not available
            do $tx$
            begin
              create text search configuration public.ontology_en (
                copy = pg_catalog.english
              );

              create text search dictionary public.ontology_en_hunspell (
                template  = ispell,
                dictfile  = en_gb,
                afffile   = en_gb,
                stopwords = english
              );

              create text search dictionary public.ontology_en_thesaurus (
                template   = thesaurus,
                dictfile   = en_ontology,
                dictionary = pg_catalog.english_stem
              );

              alter text search configuration public.ontology_en
                alter mapping
                  for asciiword, asciihword, hword_asciipart, word, hword, hword_part
                 with ontology_en_hunspell, english_stem;

              alter text search configuration public.ontology_en
                alter mapping
                  for asciiword, asciihword, hword_asciipart
                 with ontology_en_thesaurus, ontology_en_hunspell, english_stem;
            exception
              when unique_violation then null;
              when others           then raise;
            end;
            $tx$ language plpgsql;
            """,
            reverse_sql="""
            drop text search configuration public.ontology_en           cascade;
            drop text search    dictionary public.ontology_en_hunspell  cascade;
            drop text search    dictionary public.ontology_en_thesaurus cascade;
            """
        ),
    ]
