version: '3'

services:
  app:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: ./test.Dockerfile
      args:
        http_proxy: http://192.168.10.15:8080
        https_proxy: http://192.168.10.15:8080
    command: >
      sh -c "/home/config_cll/init-app.sh
      && /usr/sbin/apache2ctl -D FOREGROUND"
    volumes:
      - ../../CodeListLibrary_project:/var/www/concept_lib_sites/v1/CodeListLibrary_project/
    ports:
      - 8005:80
    expose:
      - 80
      - 443
    env_file:
      - ./app.compose.env
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - .:/data
    networks:
      default:
        aliases:
          - redis

  celery_worker:
    build:
      context: ..
      dockerfile: ./test.Dockerfile
      args:
        http_proxy: http://192.168.10.15:8080
        https_proxy: http://192.168.10.15:8080
    command: >
      sh -c "/home/config_cll/worker_start.sh"
    env_file:
      - ./app.compose.env
    volumes:
      - ../../CodeListLibrary_project:/var/www/concept_lib_sites/v1/CodeListLibrary_project/
    depends_on:
      - app
      - redis

  celery_beat:
    build:
      context: ..
      dockerfile: ./test.Dockerfile
      args:
        http_proxy: http://192.168.10.15:8080
        https_proxy: http://192.168.10.15:8080
    command: >
      sh -c "/home/config_cll/beat_start.sh"
    env_file:
      - ./app.compose.env
    volumes:
      - ../../CodeListLibrary_project:/var/www/concept_lib_sites/v1/CodeListLibrary_project/
    depends_on:
      - app
      - redis
      - celery_worker
