LOGICAL_TYPE_INCLUSION = 1
LOGICAL_TYPE_EXCLUSTION = 2

LOGICAL_TYPES = (
    (LOGICAL_TYPE_INCLUSION, 'Inclusion'),
    (LOGICAL_TYPE_EXCLUSTION, 'Exclusion'),
)

REGEX_TYPE_SIMPLE = 1
REGEX_TYPE_POSIX = 2

REGEX_TYPE_CHOICES = ((REGEX_TYPE_SIMPLE, 'simple (% only)'),
                      (REGEX_TYPE_POSIX, 'POSIX regex'))
