# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-03 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalcode', '0006_get_concept_unique_codes_live_v2_sql'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('description',)},
        ),
    ]
