apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "concept-library.fullname" . }}

spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.dns.hostName }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "concept-library.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
            path: /
            pathType: Prefix