{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "concept-library.fullname" . }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ include "concept-library.name" . }}
  endpoints:
    - port: {{ .Values.serviceMonitor.port }}
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
  {{- end }}