"""
Django settings for testing the CLL project.

Copied from the CLL project settings which were generated by
'django-admin startproject' using Django 1.10.4.

Need to remove the LDAP access for testing so that we can create dummy
users and authenticate them without locking out the test user.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

from .settings import *

from selenium import webdriver

WEBAPP_HOST = ''

# remote test features
REMOTE_TEST = False #True
REMOTE_TEST_HOST = 'http://selenium-hub:4444/wd/hub'
IMPLICTLY_WAIT = 10
TEST_SLEEP_TIME = 5

if REMOTE_TEST:
    WEBAPP_HOST = 'http://webapp-test/'

chrome_options = webdriver.ChromeOptions()
chrome_options.add_experimental_option( "prefs",{'profile.managed_default_content_settings.javascript': 'enable'})
chrome_options.add_argument('--headless')
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-dev-shm-usage")

chrome_options.add_argument("--start-maximized")
chrome_options.add_argument("--disable-gpu")
chrome_options.add_argument("--window-size=1280,800")
chrome_options.add_argument("--allow-insecure-localhost")
chrome_options.add_argument("--verbose")



CLL_READ_ONLY = True # ALWAYS TRUE FOR READ-ONLY TEST  #  get_env_value('CLL_READ_ONLY', cast='bool')
    
os.environ["DJANGO_SETTINGS_MODULE"] = "cll.read_only_test_settings"

# Keep ModelBackend around for per-user permissions and a local superuser.
AUTHENTICATION_BACKENDS = [
    # For testing, we MUST remove the LDAP back-end or the dummy users may
    # cause havoc with the security systems.
    # 'django_auth_ldap.backend.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': get_env_value('UNIT_TEST_DB_NAME'),
        'USER': get_env_value('UNIT_TEST_DB_USER'),
        'PASSWORD': get_env_value('UNIT_TEST_DB_PASSWORD'),
        'HOST': get_env_value('UNIT_TEST_DB_HOST'),
        'PORT': '',
        'TEST': {
            'NAME': get_env_value('UNIT_TEST_DB_NAME')  # TODO: check this was cl_testdatabase before!
        },
    }
}

SHOW_COOKIE_ALERT = False

