"""
Django settings for testing the CLL project.

Copied from the CLL project settings which were generated by
'django-admin startproject' using Django 1.10.4.

Need to remove the LDAP access for testing so that we can create dummy
users and authenticate them without locking out the test user.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""
import webdriver_auto_update

"""
Django settings for cll project.

For the full list of settings and their values, see
https://docs.djangoproject.com/
"""

from selenium import webdriver

from .settings import *

import wget
import subprocess
import requests
import os
import zipfile


def download_lates_driver(version, directory_driver, type_os):
    url_windows = "https://chromedriver.storage.googleapis.com/" + version + "/chromedriver_win32.zip"
    url_linux = "https://chromedriver.storage.googleapis.com/" + version + "/chromedriver_linux64.zip"

    driver_zip = ''
    if type_os == 'windows':
        driver_zip = wget.download(url_windows, out=directory_driver)

    elif type_os == 'linux':
        driver_zip = wget.download(url_linux, out=directory_driver)

    with zipfile.ZipFile(driver_zip, 'r') as downloaded_zip:
        downloaded_zip.extractall(path=directory_driver)

    os.remove(driver_zip)
    return


def check_driver(driver_directory, type_os):
    url_latest_release = "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"
    response = requests.get(url_latest_release)
    online_drive_version = response.text

    path_to_directory = os.path.abspath(driver_directory)

    try:

        cmd_run = subprocess.run(['cmd.exe','/r',path_to_directory + "/chromedriver --version"], capture_output=True, text=True)
        if IS_LINUX:
            linux_run = cmd_run
            linux_run = subprocess.run(path_to_directory + "/chromedriver --version",capture_output=True, text=True)
            cmd_run = linux_run


    except FileNotFoundError:
        print("No chromedriver")
        download_lates_driver(online_drive_version, driver_directory, type_os)
    else:
        local_drive_version = cmd_run.stdout.split()[1]
        print(f'Local version of chromedrive:{local_drive_version}')
        print(f'Web version of chromedrive:{online_drive_version}')

        if local_drive_version == online_drive_version:
            return True
        else:
            download_lates_driver(online_drive_version, driver_directory, type_os)


WEBAPP_HOST = ''

# remote test features
REMOTE_TEST = False  # True
REMOTE_TEST_HOST = 'http://selenium-hub:4444/wd/hub'
IMPLICTLY_WAIT = 10
TEST_SLEEP_TIME = 5

if REMOTE_TEST:
    WEBAPP_HOST = 'http://webapp-test/'

linux_chromdriver = check_driver('clinicalcode/tests/functional_tests','linux')
windows_chromdriver = check_driver('clinicalcode/tests/functional_tests','windows')

chrome_options = webdriver.ChromeOptions()
chrome_options.add_experimental_option(
    "prefs", {'profile.managed_default_content_settings.javascript': 'enable'})

chrome_options.add_argument('--headless')
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-dev-shm-usage")

chrome_options.add_argument("--start-maximized")
chrome_options.add_argument("--disable-gpu")
chrome_options.add_argument("--window-size=1280,800")
chrome_options.add_argument("--allow-insecure-localhost")
chrome_options.add_argument("--verbose")

os.environ["DJANGO_SETTINGS_MODULE"] = "cll.test_settings"

# Keep ModelBackend around for per-user permissions and a local superuser.
AUTHENTICATION_BACKENDS = [
    # For testing, we MUST remove the LDAP back-end or the dummy users may
    # cause havoc with the security systems.
    # 'django_auth_ldap.backend.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': get_env_value('UNIT_TEST_DB_NAME'),
        'USER': get_env_value('UNIT_TEST_DB_USER'),
        'PASSWORD': get_env_value('UNIT_TEST_DB_PASSWORD'),
        'HOST': get_env_value('UNIT_TEST_DB_HOST'),
        'PORT': '',
        'TEST': {
            'NAME':
            get_env_value('UNIT_TEST_DB_NAME'
                          )  # TODO: check this was cl_testdatabase before!
        },
    }
}

SHOW_COOKIE_ALERT = False

