name: Build Helm Chart

on:
  pull_request:
    # Only consider PRs that change files for this asset, including ci scripts
    paths:
      - '.github/workflows/concept-library-chart.yaml'
      - 'chart/concept-library/**'
    # Make sure all workflows that are "required checks" for a given
    # branch protection rule have the same paths: and branches-ignore:
    # filters. Otherwise, you can end up in a deadlock waiting on a
    # required check that will never be executed.
  push:
    # Only release off of release and maintenance branches for this asset
    branches:
      - 'master'
    # Only consider pushes that change files for this asset, including ci scripts
    paths:
      - '.github/workflows/concept-library-chart.yaml'
      - 'chart/concept-library/**'

permissions:
  contents: write
  pull-requests: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Needed to generate releases safely
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  # Job name must be unique across repo to target
  # branch protection rules "required checks" properly!
  concept-library-chart:
    uses: SwanseaUniversityMedical/workflows/.github/workflows/pr-and-release-chart.yaml@v3.0.1-charts
    with:
      job-name: concept-library-chart
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-project: ${{ vars.HARBOR_PROJECT }}
      registry-repo: serp-forms
      release-tag-format: 'Concept-Library-Chart-${version}'
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      chart: chart/concept-library
      test-command: |
        helm template $CHART --debug

    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}
