name: test dns

on:
  pull_request:
    paths:
      - '.github/workflows/concept-library-dns.yaml'
      - 'chart/concept-library/**'
    # Make sure all workflows that are "required checks" for a given
    # branch protection rule have the same paths: and branches-ignore:
    # filters. Otherwise, you can end up in a deadlock waiting on a
    # required check that will never be executed.
#  push:
#    # Only release off of release and maintenance branches for this asset
#    paths:
#      - '.github/workflows/concept-library-chart.yaml'
#      - 'chart/concept-library/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy chart
        run: |
          helm upgrade --install concept-library \
            ./chart \
            --namespace pr-${{ github.event.number }} \
            --create-namespace \
            --set dns.hostname=concept-library-pr-${{ github.event.number }}.example.com

      - name: Run test
        run: |
          kubectl apply -n pr-${{ github.event.number }} -f k8s/test-job.yaml
          kubectl set env job/concept-library-dns-test \
            HOSTNAME=concept-library-pr-${{ github.event.number }}.example.com \
            -n pr-${{ github.event.number }}

          kubectl wait --for=condition=complete job/concept-library-dns-test -n pr-${{ github.event.number }} --timeout=600s
          kubectl logs job/concept-library-dns-test -n pr-${{ github.event.number }}

      - name: Cleanup
        if: always()
        run: |
          helm uninstall concept-library -n pr-${{ github.event.number }}
          kubectl delete namespace pr-${{ github.event.number }}