name: Build Concept Library Container

on:
  pull_request:
    # Only consider PRs that change files for this asset, including ci scripts
    paths:
      - '.github/workflows/concept-library-container.yaml'
      - 'CodeListLibrary_project/**'
      - 'docker/**'
  push:
    # Only release off of release and maintenance branches for this asset
    branches:
      - 'master'
    # Only consider pushes that change files for this asset, including ci scripts
    paths:
      - '.github/workflows/concept-library-container.yaml'
      - 'CodeListLibrary_project/**'
      - 'docker/**'

permissions:
  contents: write
  pull-requests: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Needed to generate releases safely
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  concept-library-container:
    uses: SwanseaUniversityMedical/workflows/.github/workflows/pr-and-release-container.yaml@v4.0.0-containers
    with:
      job-name: concept-library-container
      comment-pr: true
      comment-release: true
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-repo: ${{ vars.HARBOR_PROJECT }}/concept-library
      release-tag-format: 'Concept-Library-${version}'
      notation-cert: ${{ vars.NOTATION_CERT }}
      build-file: docker/app/Dockerfile
      build-args: |
        server_name=conceptlibrary.saildatabank.com
        dependency_target=production.txt
    secrets:
      notation-key: ${{ secrets.NOTATION_KEY }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}
