name: Integration-test

on:
  push:
    branches: ["test-master"]
  pull_request:
    branches: ["test-master"]

jobs:
  pre-deploy-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: concept_library
          POSTGRES_USER: clluser_test
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Code and Setup
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
      - name: Install Dependencies
        run: |
          sudo apt-get install -y -q libsasl2-dev libldap2-dev libssl-dev
          python -m pip install --upgrade pip
          pip install --upgrade --upgrade-strategy eager -r docker/requirements/base.txt
      - name: Prepare Selenium and Run Browser
        uses: nanasess/setup-chromedriver@v2
      - name: Run chromedriver
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - name: Run Application and Tests
        run: |
          export $(grep -v '^#' docker/selenium-testing/env/remotetest.compose.env | xargs)
          cd CodeListLibrary_project
          python manage.py makemigrations
          python manage.py migrate
          python manage.py runserver 0.0.0.0:8000 > /dev/null &
          pytest -v -s --cov-report xml --cov . --html=report.html --self-contained-html -k "" || true
        env:
          DISPLAY: ":99"
      - name: Coverage report
        uses: 5monkeys/cobertura-action@v13
        with:
          path: CodeListLibrary_project/coverage.xml
          minimum_coverage: 25
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: CodeListLibrary_project/report.html
          retention-days: 5
