name: Integration-test

on:
  push:
    branches: [ "test-master" ]
  pull_request:
    branches: [ "test-master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

  
    steps:
    - uses: actions/checkout@v3      
    - uses: browser-actions/setup-chrome@v1
    - run: chrome --version
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install LDAP files
      run: |
        sudo apt-get install -y -q libsasl2-dev libldap2-dev libssl-dev
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docker/requirements/base.txt
    - name: Run Tests
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
        python CodeListLibrary_project/manage.py test --noinput
